# Generated by Django 3.0.8 on 2020-07-27 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shadow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=2048)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shadow', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
