# Generated by Django 3.0.8 on 2020-07-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shadow',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
