# Generated by Django 3.0.8 on 2020-07-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_shadow_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='shadow',
            name='addr',
            field=models.GenericIPAddressField(default='127.0.0.1', unpack_ipv4=True),
            preserve_default=False,
        ),
    ]
