# Generated by Django 3.0.8 on 2020-07-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_shadow_addr'),
    ]

    operations = [
        migrations.AddField(
            model_name='shadow',
            name='agent',
            field=models.TextField(default=''),
        ),
    ]
