# Generated by Django 3.0.8 on 2020-07-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_shadow_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shadow',
            name='fingerprint',
            field=models.CharField(max_length=2048, unique=True),
        ),
    ]
