# Generated by Django 3.1.2 on 2020-11-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0006_auto_20201118_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggedinuser',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
