# Generated by Django 3.1.2 on 2020-11-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0009_auto_20201121_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='languages',
            field=models.CharField(default='', max_length=100),
        ),
    ]
