# Generated by Django 3.1.4 on 2020-12-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0010_auto_20201123_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='shadow_priviledges',
        ),
        migrations.AddField(
            model_name='profile',
            name='preferences',
            field=models.JSONField(default=dict),
        ),
    ]
