# Generated by Django 3.1.4 on 2020-12-08 18:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0010_auto_20201123_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='shadow_priviledges',
        ),
        migrations.AddField(
            model_name='profile',
            name='preferences',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='profile',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), default=list, null=True, size=None),
        ),
    ]
