# Generated by Django 3.1.2 on 2020-12-08 14:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0011_auto_20201208_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=5, null=True), size=None),
        ),
    ]
