# Generated by Django 3.1.2 on 2020-12-08 14:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0012_auto_20201208_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), blank=True, null=True, size=None),
        ),
    ]
