# Generated by Django 3.1.2 on 2020-12-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0013_auto_20201208_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='shadow_priviledges',
        ),
        migrations.AddField(
            model_name='profile',
            name='preferences',
            field=models.JSONField(default=dict),
        ),
    ]
