# Generated by Django 3.1.4 on 2020-12-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0013_auto_20201209_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='username_old',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='username_prefix',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='username_suffix',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
