# Generated by Django 3.1.2 on 2020-11-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='ua',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='User agent'),
        ),
    ]
