# Generated by Django 3.0.8 on 2020-07-25 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tagmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objecttag',
            name='abstract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objs', to='tagmanager.AbstractTag'),
        ),
    ]
