# Generated by Django 3.0.8 on 2020-07-25 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tagmanager', '0002_auto_20200725_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('issuer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_tags', to=settings.AUTH_USER_MODEL)),
                ('objtag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individuals', to='tagmanager.ObjectTag')),
            ],
        ),
    ]
