# Generated by Django 3.0.8 on 2020-07-25 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tagmanager', '0003_individualtag'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTagManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='individualtag',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individuals', to='tagmanager.UserTagManager'),
        ),
    ]
