# Generated by Django 3.0.8 on 2020-07-25 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tagmanager', '0004_auto_20200725_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualtag',
            name='issuer',
        ),
        migrations.AddField(
            model_name='usertagmanager',
            name='issuer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_tags', to=settings.AUTH_USER_MODEL),
        ),
    ]
