# Generated by Django 3.0.8 on 2020-07-25 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tagmanager', '0005_auto_20200725_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertagmanager',
            name='issuer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_tags', to=settings.AUTH_USER_MODEL),
        ),
    ]
