# Generated by Django 3.0.8 on 2020-08-31 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tagmanager', '0007_auto_20200725_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individualtag',
            old_name='objtag',
            new_name='object',
        ),
        migrations.AlterField(
            model_name='objecttag',
            name='abstract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='tagmanager.AbstractTag'),
        ),
    ]
