# Generated by Django 3.0.8 on 2020-08-31 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagmanager', '0008_auto_20200831_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertagmanager',
            old_name='issuer',
            new_name='user',
        ),
    ]
