# Generated by Django 3.0.8 on 2020-08-31 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tagmanager', '0009_auto_20200831_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objecttag',
            name='abstract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individuals', to='tagmanager.AbstractTag'),
        ),
    ]
