# Generated by Django 3.1.2 on 2020-10-28 16:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tagmanager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Narrative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versioning', models.BooleanField(default=True)),
                ('title', models.CharField(default='Başlıklı hikaye', max_length=100)),
                ('slug', models.SlugField(max_length=100, null=True, unique=True)),
                ('body', models.TextField(null=True)),
                ('html', models.TextField(null=True)),
                ('sketch', models.BooleanField(default=False)),
                ('uuid', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='narratives', to=settings.AUTH_USER_MODEL)),
                ('tags', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='narrative', to='tagmanager.tagmanager')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='SoundRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='voice-records', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'aac', 'wav', 'opus'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NarrativeVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Başlıklı hikaye', max_length=100)),
                ('slug', models.SlugField(max_length=100, null=True, unique=True)),
                ('body', models.TextField(null=True)),
                ('html', models.TextField(null=True)),
                ('sketch', models.BooleanField(default=False)),
                ('uuid', models.UUIDField()),
                ('version', models.PositiveIntegerField()),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='notebook.narrative')),
                ('sound', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='narratives', to='notebook.soundrecord')),
            ],
        ),
    ]
