# Generated by Django 3.1.2 on 2020-10-30 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='narrativeversion',
            options={'ordering': ('-version',)},
        ),
        migrations.AddField(
            model_name='narrativeversion',
            name='readonly',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='narrativeversion',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
