# Generated by Django 3.0.8 on 2020-07-23 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tagmanager', '0001_initial'),
        ('notebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='narrative',
            name='tagman',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='narrative', to='tagmanager.TagManager'),
        ),
    ]
