# Generated by Django 3.0.8 on 2020-07-27 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notebook', '0002_narrative_tagman'),
    ]

    operations = [
        migrations.AddField(
            model_name='narrative',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='narratives', to=settings.AUTH_USER_MODEL),
        ),
    ]
