# Generated by Django 3.1.2 on 2020-11-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0003_narrative_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='narrativeversion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
