# Generated by Django 3.0.8 on 2020-07-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0003_narrative_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='narrative',
            name='sketch',
            field=models.BooleanField(default=False),
        ),
    ]
