# Generated by Django 3.1.2 on 2020-11-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0004_narrativeversion_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='narrative',
            name='lead',
            field=models.TextField(blank=True, null=True, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='narrative',
            name='body',
            field=models.TextField(null=True, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='narrative',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='narrative',
            name='html',
            field=models.TextField(null=True, verbose_name='HTML'),
        ),
        migrations.AlterField(
            model_name='narrative',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Publication date'),
        ),
        migrations.AlterField(
            model_name='narrative',
            name='sketch',
            field=models.BooleanField(default=False, verbose_name='Sketch'),
        ),
        migrations.AlterField(
            model_name='narrative',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='narrative',
            name='title',
            field=models.CharField(default='Başlıklı hikaye', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='narrative',
            name='uuid',
            field=models.UUIDField(verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='narrative',
            name='versioning',
            field=models.BooleanField(default=True, verbose_name='Keeps seperate versions'),
        ),
    ]
