# Generated by Django 3.0.8 on 2020-07-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0004_narrative_sketch'),
    ]

    operations = [
        migrations.AddField(
            model_name='narrative',
            name='uuid',
            field=models.UUIDField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='narrative',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
