# Generated by Django 3.1.2 on 2020-11-18 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0005_auto_20201114_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='narrativeversion',
            name='created_at',
        ),
        migrations.CreateModel(
            name='NarrativeTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('tr', 'Türkçe')], max_length=5)),
                ('title', models.CharField(default='404', max_length=100)),
                ('slug', models.SlugField(max_length=100, null=True, unique=True)),
                ('body', models.TextField(null=True)),
                ('html', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='notebook.narrative')),
            ],
        ),
    ]
