# Generated by Django 3.0.8 on 2020-07-31 10:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0005_auto_20200729_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='narrative',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
