# Generated by Django 3.1.2 on 2020-11-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0006_auto_20201118_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='narrative',
            name='language',
            field=models.CharField(default='en-us', max_length=5),
        ),
        migrations.AlterField(
            model_name='narrative',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='narrativetranslation',
            name='language',
            field=models.CharField(max_length=5),
        ),
    ]
