# Generated by Django 3.0.8 on 2020-08-30 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0007_auto_20200808_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='narrative',
            old_name='tagman',
            new_name='tags',
        ),
    ]
