# Generated by Django 3.1.1 on 2020-09-15 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0008_auto_20200830_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='narrative',
            name='sound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='narratives', to='notebook.soundrecord'),
        ),
    ]
