# Generated by Django 3.1.2 on 2020-11-21 15:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tagmanager', '0001_initial'),
        ('notebook', '0009_auto_20201121_1830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='narrative',
            options={'ordering': ('-published_at', '-created_at')},
        ),
        migrations.RemoveField(
            model_name='narrative',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='narrativeversion',
            name='sound',
        ),
        migrations.AddField(
            model_name='narrativetranslation',
            name='tags',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='narrative', to='tagmanager.tagmanager'),
        ),
        migrations.AddField(
            model_name='narrativeversion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='narrativeversion',
            name='edited_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last edited at'),
        ),
        migrations.AddField(
            model_name='narrativeversion',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('tr', 'Türkçe'), ('fr', 'Français'), ('de', 'Deustch'), ('ru', 'русский')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='narrativeversion',
            name='lead',
            field=models.TextField(blank=True, null=True, verbose_name='Summary'),
        ),
        migrations.AddField(
            model_name='narrativeversion',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Publication date'),
        ),
        migrations.AlterField(
            model_name='narrative',
            name='sketch',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='narrative',
            name='uuid',
            field=models.UUIDField(unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='narrativeversion',
            name='body',
            field=models.TextField(null=True, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='narrativeversion',
            name='html',
            field=models.TextField(null=True, verbose_name='HTML'),
        ),
        migrations.AlterField(
            model_name='narrativeversion',
            name='sketch',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='narrativeversion',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='narrativeversion',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='narrativeversion',
            name='uuid',
            field=models.UUIDField(unique=True, verbose_name='UUID'),
        ),
    ]
