# Generated by Django 3.1.2 on 2020-11-21 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0010_auto_20201121_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='narrativetranslation',
            name='body',
        ),
        migrations.RemoveField(
            model_name='narrativetranslation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='narrativetranslation',
            name='html',
        ),
        migrations.RemoveField(
            model_name='narrativetranslation',
            name='language',
        ),
        migrations.RemoveField(
            model_name='narrativetranslation',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='narrativetranslation',
            name='title',
        ),
        migrations.RemoveField(
            model_name='narrativetranslation',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='narrativeversion',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='notebook.narrativetranslation'),
        ),
    ]
