# Generated by Django 3.1.2 on 2020-11-23 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notebook', '0012_auto_20201121_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='narrative',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='narratives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='narrative',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('tr', 'Türkçe'), ('fr', 'Français'), ('de', 'Deustch'), ('ru', 'русский'), ('es', 'Español')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='narrative',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='narrativetranslation',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('tr', 'Türkçe'), ('fr', 'Français'), ('de', 'Deustch'), ('ru', 'русский'), ('es', 'Español')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='narrativetranslation',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='narrativeversion',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('tr', 'Türkçe'), ('fr', 'Français'), ('de', 'Deustch'), ('ru', 'русский'), ('es', 'Español')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='narrativeversion',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Title'),
        ),
    ]
