# Generated by Django 3.1.4 on 2020-12-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0013_auto_20201123_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='narrative',
            name='title',
        ),
        migrations.AddField(
            model_name='narrative',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='narrativetranslation',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='narrativeversion',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
