# Generated by Django 3.1.4 on 2020-12-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0014_auto_20201209_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='narrativetranslation',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
