# Generated by Django 3.1.4 on 2020-12-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0016_auto_20201209_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='narrative',
            name='raw',
            field=models.TextField(blank=True, null=True, verbose_name='Raw'),
        ),
        migrations.AddField(
            model_name='narrativetranslation',
            name='raw',
            field=models.TextField(blank=True, null=True, verbose_name='Raw'),
        ),
        migrations.AddField(
            model_name='narrativeversion',
            name='raw',
            field=models.TextField(blank=True, null=True, verbose_name='Raw'),
        ),
    ]
