# Generated by Django 3.1.4 on 2020-12-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0017_auto_20201209_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='narrativetranslation',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='narrativeversion',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title'),
        ),
    ]
