# Generated by Django 3.1.4 on 2020-12-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0018_auto_20201209_2318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='narrativetranslation',
            options={'ordering': ('-edited_at', 'edited_at')},
        ),
        migrations.AlterField(
            model_name='narrative',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('tr', 'Türkçe')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='narrativetranslation',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('tr', 'Türkçe')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='narrativeversion',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('tr', 'Türkçe')], max_length=5, null=True),
        ),
    ]
