# Generated by Django 3.1.4 on 2020-12-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0020_auto_20201211_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='narrative',
            name='body',
        ),
        migrations.RemoveField(
            model_name='narrative',
            name='html',
        ),
        migrations.RemoveField(
            model_name='narrative',
            name='language',
        ),
        migrations.RemoveField(
            model_name='narrative',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='narrative',
            name='public',
        ),
        migrations.RemoveField(
            model_name='narrative',
            name='raw',
        ),
        migrations.RemoveField(
            model_name='narrative',
            name='sketch',
        ),
        migrations.RemoveField(
            model_name='narrative',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='narrativetranslation',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='narrativeversion',
            name='is_published',
        ),
        migrations.AlterField(
            model_name='narrative',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='narrativetranslation',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='narrativetranslation',
            name='raw',
            field=models.TextField(blank=True, null=True, verbose_name='Raw Text'),
        ),
        migrations.AlterField(
            model_name='narrativeversion',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='narrativeversion',
            name='raw',
            field=models.TextField(blank=True, null=True, verbose_name='Raw Text'),
        ),
        migrations.DeleteModel(
            name='SoundRecord',
        ),
    ]
